version: '3.8'

services:
  be-app:
    image: demo
    build: .
    ports:
      - "8080:80"
    restart: always
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/foodbe-db
      DB_USERNAME: admin
      DB_PASSWORD: Zaq12wsxcde3
      LOG_LEVEL: INFO
    depends_on:
      - db

  db:
    image: postgres
    container_name: foodbe-db
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: Zaq12wsxcde3